# exclude: ^custom_components|www|themes|home-assistant.log*
# repos:
# - hooks:
#   - id: trailing-whitespace
#   - exclude: ^.HA_VERSION|README.md|node-red|.json
#     id: end-of-file-fixer
#   - id: check-added-large-files
#   - id: check-json
#   - id: check-merge-conflict
#   - id: check-symlinks
#   - id: mixed-line-ending
#   - id: check-xml
#   - args:
#     - --unsafe
#     id: check-yaml
#   - id: sort-simple-yaml
#   repo: https://github.com/pre-commit/pre-commit-hooks
#   rev: v2.3.0
# - hooks:
#   - id: yamllint
#   repo: https://github.com/adrienverge/yamllint.git
#   rev: v1.17.0
# - hooks:
#   - id: commitizen
#     stages:
#     - commit-msg
#   repo: https://github.com/commitizen-tools/commitizen
#   rev: v2.20.0
