---
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

discovery:

homeassistant:
  packages: !include_dir_named integrations
  allowlist_external_dirs:
    - !secret allow_list_ext_dir

frontend:
  themes: !include_dir_merge_named themes

notify:
  - name: Healthchecks.io HA Daily Backup
    platform: rest
    resource: https://hc-ping.com/9276a26c-77bb-4aee-95e0-7d3e63769d33

# Text to speech
tts:
  - platform: google_translate

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
    - 10.1.2.3/32
    - 10.1.2.129/32
scene: !include_dir_list scenes
lovelace: !include lovelace.yaml

alexa:
  smart_home:
    locale: en-GB
    filter:
      include_domains:
        - light
        - cover
        - switch
        - scene
      exclude_entity_globs:
        - light.living_room_wall_light_*
        - light.kitchen_light_*
google_assistant:
  project_id: !secret google_assistant_project_id
  service_account: !include google_assistant_service_account.json
  report_state: true
  exposed_domains:
    - light
    - cover
    - switch
    - scene
  entity_config:
    switch.octoprint_cancel_print:
      expose: false
    switch.octoprint_connect_to_printer:
      expose: false
    switch.octoprint_psu:
      expose: false
    switch.octoprint_pause_print:
      expose: false
    switch.octoprint_shutdown_system:
      expose: false
    switch.octoprint_camera_snapshot:
      expose: false
    switch.octoprint_emergency_stop:
      expose: false
logger:
  default: warning

device_tracker:
  - platform: icloud3
    username: !secret icloud3_username
    password: !secret icloud3_password
