---
alias: Medication Reminder - Medication Taken
id: 9ec77314-81ce-43eb-a9b1-16d55b7965fc

trigger:
  - entity_id:
      - input_boolean.medication_taken
    platform: state
    to: "on"

action:
  - service: input_number.decrement
    target:
      entity_id:
        - input_number.prep_tablets
  - service: input_number.decrement
    target:
      entity_id:
        - input_number.sertraline_tablets
  - service: notify.mobile_app_richard_samsung_phone
    data:
      message: "Medication marked as taken"
