---
alias: Medication Reminder - Medication Taken
id: 9ec77314-81ce-43eb-a9b1-16d55b7965fc

trigger:
  - entity_id:
      - input_boolean.medication_taken
    platform: state
    to: "on"

action:
  - alias: 'Decrease PREP'
    service: rest_command.grocy_consume
    data:
      productId: 64
      amount: 1
  - alias: 'Decrease Sertaline'
    service: rest_command.grocy_consume
    data:
      productId: 65
      amount: 1
  - alias: 'Decrease Spray'
    service: rest_command.grocy_consume
    data:
      productId: 63
      amount: 4
  - alias: 'Decrease Multivitamin'
    service: rest_command.grocy_consume
    data:
      productId: 93
      amount: 1
  - alias: 'Decrease Vitamin D'
    service: rest_command.grocy_consume
    data:
      productId: 94
      amount: 1
  - service: notify.mobile_app_richard_samsung_phone
    data:
      message: "Medication marked as taken"
