---
alias: Medication Reminder - Reminder Notification
id: b663961f-b1cf-409a-af44-0b4cb86a4c7e

trigger:
  - platform: time_pattern
    hours: "/1"
    minutes: 0

condition:
  condition: and
  conditions:
    - condition: state
      entity_id: input_boolean.medication_taken
      state: "off"
    - condition: time
      after: '09:00:00'
      before: '00:00:00'

action:
  - service: notify.all_ios_devices
    data:
      message: "Reminder, take your medication"
      data:
        actions:
          - action: "richard_medication_taken"
            title: "I've taken it."
