---
alias: Medication Reminder - Reset Medication Input
id: 55b8dfcb-05eb-4a41-a10b-8cf44365a72f

trigger:
  - platform: time
    at: "00:00"

action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.medication_taken
