---
alias: Medication Reminder - Trigger Medication Taken

variables:
  tags: a410bed4-013f-4d43-9596-f225844aeedf

trigger:
  - platform: event
    event_type:
      - tag_scanned
      - mobile_app_notification_action

condition:
  - condition: or
    conditions:
      - condition: template
        value_template: "{{ trigger.event.data.tag_id in tags}}"
      - condition: template
        value_template: "{{ trigger.event.data.action == 'richard_medication_taken' }}"

action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.medication_taken
