---
alias: Kitchen - Washing Machine - Finished
id: c61b49f6-f7ff-4976-a4a1-cf6ad04cbc8b

trigger:
  - platform: state
    entity_id: input_select.washing_machine_status
    from: "Running"
    to: "Idle"

action:
  - alias: "Actions when washing machine is finished"
    choose:
    - conditions:
        - alias: "Cleaning mode is on"
          condition: state
          entity_id: input_boolean.washing_machine_cleaning
          state: "on"
      sequence:
        - alias: "Send notification"
          service: notify.all_ios_devices
          data:
            message: 'Washing machine has finished cleaning'
        - alias: "Turn off cleaning mode"
          service: input_boolean.turn_off
          target:
            entity_id: input_boolean.washing_machine_cleaning
    - conditions:
        - alias: "Cleaning mode is off"
          condition: state
          entity_id: input_boolean.washing_machine_cleaning
          state: "off"
      sequence:
        - alias: "Drysoon check"
          choose:
          - conditions:
            - alias: "DrySoon on"
              condition: state
              entity_id: switch.drysoon
              state: "on"
            sequence:
              - alias: "Send notification"
                service: notify.all_ios_devices
                data:
                  message: 'Washing machine finished. DrySoon already on'
          - conditions:
            - alias: "DrySoon on"
              condition: state
              entity_id: switch.drysoon
              state: "off"
            sequence:
              - alias: "Call DrySoon Notification Script"
                service: script.washing_machine_drysoon_notification
          default:
          - alias: "Send notification"
            service: notify.all_ios_devices
            data:
              message: "Washing machine finished. Can't determine DrySoon state."
