---
alias: Kitchen - Washing Machine - Running
id: 818f8a02-d9ff-4ee7-a9b0-03a128936c8c

trigger:
  - platform: numeric_state
    entity_id: sensor.washing_machine_current
    above: 0.05
    for: "00:05"

action:
  - alias: "Set washing machine status running"
    service: input_select.select_option
    target:
      entity_id: input_select.dishwasher_status
    data:
      option: 'Running'
