---
alias: Kitchen - Nespresso - Vend Coffee
id: 37cf3834-a157-4499-8316-a3bbf8421f22

trigger:
  - platform: state
    entity_id: input_boolean.nespresso_lid
    from: "on"
    to: "off"

condition:
  - alias: "Cleaning mode off"
    condition: state
    entity_id: input_boolean.nespresso_cleaning
    state: "off"

action:
  - alias: "Wait for vibration"
    wait_template: "{{ is_state('sensor.nespresso_action', 'vibration') }}"
    timeout: "00:05"
  - alias: "Wait for lid to open"
    wait_template: "{{ is_state('input_boolean.nespresso_lid', 'on') }}"
    timeout: "00:05"
  - alias: "Increase nespresso cycle"
    service: counter.increment
    target:
      entity_id: counter.nespresso_cycles
  - alias: "Send notification"
    service: notify.mobile_app_richard_samsung_phone
    data:
      message: 'Coffee vended, enjoy!'
      data:
        ttl: 0
        priority: 'high'
