---
alias: Kitchen - Nespresso - Lid
id: 64b7934c-fc2b-4ce4-851e-f68ce03fa12a

trigger:
  - platform: state
    entity_id: sensor.nespresso_angle

action:
- alias: "Set lid open or closed"
  choose:
  - conditions:
    - alias: "Lid is closed"
      condition: state
      entity_id: sensor.nespresso_angle
      state: '1'
    sequence:
      - alias: "Set lid closed"
        service: input_boolean.turn_off
        target:
          entity_id: input_boolean.nespresso_lid
  default:
      - alias: "Set lid open"
        service: input_boolean.turn_on
        target:
          entity_id: input_boolean.nespresso_lid
