---
alias: Xbox - Event - Gaming mode yes
id: 6160fb9e-d74e-4ed8-b74e-a8df534f4b62

trigger:
  - platform: event
    event_type:
      - mobile_app_notification_action

condition:
  - condition: template
    value_template: "{{ trigger.event.data.action == 'xbox_gaming_mode_yes' }}"

action:
- alias: "Turn on gaming mode"
  service: scene.turn_on
  target:
    entity_id: scene.bedroom_xbox
