---
alias: Xbox - Event - Lights On
id: 6770acbb-4d4f-496c-8cf1-1060406fb0c2

trigger:
  - platform: event
    event_type:
      - mobile_app_notification_action

condition:
  - condition: template
    value_template: "{{ trigger.event.data.action == 'xbox_lights_on' }}"

action:
- alias: "Turn on lights"
  service: scene.turn_on
  target:
    entity_id: scene.bedroom_lights_on
