---
alias: Xbox - Game Stop
id: d8614d3e-39ae-4205-b3a4-44ea35868d27

trigger:
  - platform: state
    entity_id: binary_sensor.rj175_in_game
    from: "on"
    to: "off"

condition:
- alias: "Gaming mode has to be on"
  condition: state
  entity_id: input_boolean.xbox_gaming_mode
  state: "on"

action:
  - alias: "Toggle gaming mode"
    service: input_boolean.turn_off
    target:
      entity_id: input_boolean.xbox_gaming_mode
  - alias: "Send Message to Phone"
    service: notify.mobile_app_richard_samsung_phone
    data:
      message: 'Xbox game finished, set lights?'
      data:
        ttl: 0
        priority: 'high'
        actions:
          - action: 'xbox_lights_dimmed'
            title: 'Dimmed'
          - action: 'xbox_lights_on'
            title: 'On'
          - action: 'xbox_lights_off'
            title: 'Off'
