---
alias: Xbox - Game Starts
id: 9125a5c4-5c68-419b-93c6-c8d895a0fd01

trigger:
  - platform: state
    entity_id: binary_sensor.rj175_in_game
    from: "off"
    to: "on"

action:
- alias: "Send Message to Phone"
  service: notify.all_ios_devices
  data:
    message: 'Xbox game started, enable gaming mode?'
    data:
      actions:
        - action: 'xbox_gaming_mode_yes'
          title: 'Yes'
        - action: 'xbox_gaming_mode_no'
          title: 'No'
