---
alias: Xbox - on xbox power on, turn on chromecast
id: 0ff0d57c-d9b9-4c16-a25a-d4f5fde27ddb

trigger:
  - platform: state
    entity_id:
      - media_player.bedroom_xbox
    to: 'on'
    from: 'off'

action:
  - service: media_player.turn_on
    target:
      entity_id: media_player.bedroom_tv
