---
alias: Xbox - Game Starts

trigger:
  - platform: state
    entity_id: binary_sensor.rj175_in_game
    from: "off"
    to: "on"

action:
- alias: "Send Message to Phone"
  service: notify.mobile_app_richard_samsung_phone
  data:
    message: 'Xbox game started, enable gaming mode?'
    data:
      ttl: 0
      priority: 'high'
      actions:
        - action: 'xbox_gaming_mode_yes'
          title: 'Yes'
        - action: 'xbox_gaming_mode_no'
          title: 'No'
