---
alias: Xbox - Event - Lights Dimmed
id: 24db3f04-5841-4f9b-9803-772b5d40554e

trigger:
  - platform: event
    event_type:
      - mobile_app_notification_action

condition:
  - condition: template
    value_template: "{{ trigger.event.data.action == 'xbox_lights_dimmed' }}"

action:
- alias: "Turn on dimmed lights"
  service: scene.turn_on
  target:
    entity_id: scene.bedroom_lights_dimmed
