---
alias: Xbox - Event - Lights Off

trigger:
  - platform: event
    event_type:
      - mobile_app_notification_action

condition:
  - condition: template
    value_template: "{{ trigger.event.data.action == 'xbox_lights_off' }}"

action:
- alias: "Turn off lights"
  service: scene.turn_on
  target:
    entity_id: scene.bedroom_lights_off