---
alias: Xbox - Event - Lights On

trigger:
  - platform: event
    event_type:
      - mobile_app_notification_action

condition:
  - condition: template
    value_template: "{{ trigger.event.data.action == 'xbox_lights_on' }}"

action:
- alias: "Turn on lights"
  service: scene.turn_on
  target:
    entity_id: scene.bedroom_lights_on
