---
alias: Cameras - Arm
id: 678dd689-fb08-4869-8b5e-69c7d96f976e

trigger:
  - entity_id: input_boolean.cameras_armed
    platform: state
    to: 'on'

action:
  - service: tapo_control.set_privacy_mode
    entity_id:
      - camera.hallway_hd
      - camera.hallway_sd
      - camera.living_room_hd
      - camera.living_room_sd
    data:
      privacy_mode: 'off'
  - service: tapo_control.ptz
    entity_id:
      - camera.hallway_hd
      - camera.hallway_sd
      - camera.living_room_hd
      - camera.hallway_sd
    data:
      preset: '2'
