---
alias: Medication Reminder Night - Reset Medication Input
id: aa9c6e25-b9a1-4b84-9e69-5f19fea1240b

trigger:
  - platform: time
    at: "09:00"

action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.medication_taken_night
