button_card_templates: !include_dir_merge_named ../../minimalist-templates/
views:
  - title: Minimalist
    cards:
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: custom:button-card
            template: custom_chip_door
            variables:
              door_sensor: binary_sensor.front_door_contact
          - type: 'custom:button-card'
            template: chip_icon_state
            variables:
              ulm_chip_icon_state_icon: '🎥'
              ulm_chip_icon_state_entity: input_boolean.cameras_armed
          - type: custom:button-card
            template: edge
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: custom:button-card
            template: chip_temperature
            variables:
              ulm_chip_temperature_inside: sensor.room_1_temperature
              ulm_chip_temperature_outside: sensor.restalrig_temperature_daily
              ulm_chip_temperature_weather: weather.met_office_restalrig_daily
          - type: 'custom:button-card'
            template: chip_icon_state
            variables:
              ulm_chip_icon_state_icon: '🔥'
              ulm_chip_icon_state_entity: climate.room_1
          - type: 'custom:button-card'
            template: chip_icon_state
            variables:
              ulm_chip_icon_state_icon: '💧'
              ulm_chip_icon_state_entity: binary_sensor.hot_water_power
          - type: custom:button-card
            template: edge
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: 'custom:button-card'
            template: card_person
            variables:
              ulm_card_person_entity: person.richard
              ulm_card_person_use_entity_picture: false
            tap_action:
              action: navigate
              navigation_path: /minimalist-views/person_richard
          - type: 'custom:button-card'
            template: card_person
            variables:
              ulm_card_person_entity: person.ryan
              ulm_card_person_use_entity_picture: false
          - type: custom:button-card
            template: edge
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: custom:button-card
            template: title
            name: Rooms
          - type: custom:button-card
            template: edge
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: custom:button-card
            template: card_navigate
            variables:
              ulm_card_navigate_path: /minimalist-views/bedroom
              ulm_card_navigate_title: Bedroom
              ulm_card_navigate_icon: mdi:bed-outline
          - type: custom:button-card
            template: card_navigate
            variables:
              ulm_card_navigate_path: /minimalist-views/second_bedroom
              ulm_card_navigate_title: Second Bedroom
              ulm_card_navigate_icon: mdi:bed-outline
          - type: custom:button-card
            template: edge
      - type: horizontal-stack
        cards:
          - type: custom:button-card
            template: edge
          - type: custom:button-card
            template: card_navigate
            variables:
              ulm_card_navigate_path: /minimalist-views/living_room
              ulm_card_navigate_title: Living Room
              ulm_card_navigate_icon: mdi:sofa-outline
          - type: custom:button-card
            template: card_navigate
            variables:
              ulm_card_navigate_path: /minimalist-views/kitchen
              ulm_card_navigate_title: Kitchen
              ulm_card_navigate_icon: mdi:fridge-outline
          - type: custom:button-card
            template: edge
