---
alias: Bedroom - Movie Resume
id: 6587c5cc-5c55-4718-b910-7491af340097
trigger:
  platform: state
  entity_id:
    - media_player.bedroom_tv
  to: 'playing'
  from: 'paused'

condition:
  - alias: "Movie scene is enabled"
    condition: state
    entity_id: input_boolean.bedroom_movie_scene
    state: "on"

action:
  - service: scene.turn_on
    entity_id: scene.bedroom_movie
