---
alias: Bedroom - Sunset
id: b8184d39-86ee-42a1-bbb5-d0b1bbff51a4

trigger:
  - platform: sun
    event: sunset
    offset: "00:30:00"

action:
  - alias: "close curtains"
    service: cover.close_cover
    target:
      entity_id: cover.bedroom_curtains
