---
alias: System - Backup Daily
id: f2082b6a-61fb-48fa-ad1c-d05f2d4d4020

trigger:
  - platform: time
    at: "00:00"

action:
  - service: hassio.backup_full
    data:
      name: "daily_backup_{{ now().strftime('%Y_%m_%d_%H_%M') }}"
