---
alias: Home - Home
id: 9ba97b2f-2e8c-4779-aff7-b1f606652a14

trigger:
  - platform: state
    entity_id: group.all_people
    from: "not_home"
    to: "home"

action:
  - alias: "Turn cameras off"
    service: input_boolean.turn_off
    target:
      entity_id: input_boolean.cameras_armed
  - alias: "Turn away mode off"
    service: input_boolean.turn_off
    target:
      entity_id: input_boolean.home_empty
  - alias: "Sun below"
    condition: state
    entity_id: sun.sun
    state: "below_horizon"
  - alias: "Turn on living room lights"
    service: scene.turn_on
    target:
      entity_id: scene.living_room_lights_on
