esphome:
  name: bedroom

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "awgI+pDQMKBuPriSk4RDjkhoMjMeeK5J/jBKVwurS2E="

ota:
  password: "5dbf07ddd5da0fe9fc8c97866ad0be89"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bedroom Fallback Hotspot"
    password: "mXlHzIivtbcX"

captive_portal:

esp32_ble_tracker:

binary_sensor:
  # Presence based on MAC address
  - platform: ble_presence
    mac_address: A4:C3:37:AF:D5:DA
    name: "ESP32 BLE Tracker iPhone"