esphome:
  name: plant

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret plant_api_encryption_key

ota:
  password: !secret plant_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Plant Fallback Hotspot"
    password: !secret plant_fallback_wifi_password

captive_portal:

sensor:
  - platform: adc
    pin: GPIO36
    attenuation: auto
    name: "Soil Moisture 1"
    unit_of_measurement: "%"
    device_class: humidity
    icon: "mdi:watering-can"
    filters:
      - calibrate_linear:
          - 2.48 -> 0
          - 1.00 -> 100
    update_interval: 20s
    accuracy_decimals: 0

  - platform: adc
    pin: GPIO36
    attenuation: auto
    name: "Soil Voltage 1"
    unit_of_measurement: "V"
    device_class: voltage
    update_interval: 20s
    accuracy_decimals: 2
    
