esphome:
  name: rfid

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret rfid_api_encryption_key

ota:
  password: !secret rfid_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Rfid Fallback Hotspot"
    password: !secret rfid_fallback_wifi_password

captive_portal:

spi:

rc522_spi:
  cs_pin: GPIO15

binary_sensor:
  - platform: rc522
    uid: 74-10-37-94
    name: "RC522 RFID Tag"
