---
alias: 3D Printer - 75 Percent Complete
id: e37e128f-47af-4f22-b30a-81808aa627f7

trigger:
  platform: numeric_state
  entity_id:
    - sensor.octoprint_job_percentage
  above: 75

action:
  - service: notify.all_ios_devices
    data:
      message: "3D print job at {{ states('sensor.octoprint_job_percentage') }}%. Estimated completion in {{ as_timestamp(states('sensor.octoprint_estimated_finish_time')) | timestamp_custom('%I:%M %p on %d/%m/%Y', False)}}"
