---
alias: 3D Printer - Job Finished
id: 443129e1-8f39-49d5-a516-19ef290ee9cc

trigger:
  platform: state
  entity_id:
    - sensor.octoprint_current_state
  from: "Printing"
  to: "Operational"

action:
  - service: notify.all_ios_devices
    data:
      message: "3D print job finished!"
