---
# Taken from https://github.com/BeardedTinker/Home-Assistant_Config/blob/master/.github/workflows/main.yml
name: Home Assistant CI - Linting

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Getting your configuration from GitHub
        uses: actions/checkout@v1
      - name: Running YAMLlint
        uses: ibiqlik/action-yamllint@v1
        with:
          config_file: .github/yamllint-config.yml
  remarklint:
    runs-on: ubuntu-18.04
    steps:
      - name: Getting your configuration from GitHub
        uses: actions/checkout@v1
      - name: Running Remark lint
        uses: "docker://pipelinecomponents/remark-lint:latest"
        continue-on-error: true
        with:
          args: "remark --ignore-path custom_components --no-stdout --color --frail --use preset-lint-recommended ."
